### ISSUE TITLE
Testimonials are not responsive in mobile view

### ISSUE THREAD

**Issue by MRIDUL-MB** [sef-global/sef-site#1128]
**Describe the bug**
Font size in mobile view.

**To Reproduce**
1. Go to 'https://sefglobal.org/'
2. Scroll down to 'last page'
4. Glitch in font size

**Expected behavior**
Reduce the font size such that everything should be see clear.

**Screenshots**
![image](https://user-images.githubusercontent.com/53037689/137746755-41b6ed34-be15-4447-9b65-89b4350d6eb1.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max 
 - OS:  14.6
 - Browser: firefox
 - Version: latest

**Comment by Piumal1999** [comment]
Hi @MRIDUL-MB, Thanks for creating the issue. Please let us know if you are working on this issue, so we can assign you to the issue.

Btw, I found that the tablet view also have this issue. 
![image](https://user-images.githubusercontent.com/27498587/137765733-4fd83f63-811c-4d70-8ca6-85729928467e.png)

**Comment by Piumal1999** [comment]
**Note:** We are using the same component in the upspeak page(https://sefglobal.org/upspeak/). So, check both pages when fixing this bug.

**Comment by MRIDUL-MB** [comment]
yeah, I am working on it, assign it to me.

**Comment by MRIDUL-MB** [comment]
label it as hactoberfest

**Comment by jayasanka-sack** [comment]
@akeel230 @Piumal1999 Is this fixed?

**Comment by akeel230** [comment]
@jayasanka-sack @Piumal1999 although the responsiveness seems to be a bit off in the inspect option. in actual smaller screen mobiles, the problem is not seen.
![Screenshot (717)](https://user-images.githubusercontent.com/83522139/148980943-8abd4b85-33d7-450c-91a2-2c7abb4263b9.png)
![photo_2022-01-11_21-52-04](https://user-images.githubusercontent.com/83522139/148981127-f6c2d21e-fa13-4b27-8c63-9b8e8829358b.jpg)
.

**Comment by jayasanka-sack** [comment]
Thanks @akeel230 !

Closing the issue because it has been already fixed.
