### ISSUE TITLE
Increase the gap between Description and Project section in engineering page

### ISSUE THREAD

**Issue by RandilaP** [sef-global/sef-site#1500]
**Describe the bug**
On the engineering page, it needs to increase the gap between the description and Project sections

**Screenshots**
![image](https://user-images.githubusercontent.com/106733522/214476123-24b76fc0-0f33-42dd-98eb-317a94b849fa.png)

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
I think I asked to increase the gap in this from @jayasanka-sack ayya or from @anjula-sack ayya, one of them told it is ok no need to fix it @RandilaP

**Comment by RandilaP** [comment]
@YoshithaRathnayake I asked from @jayasanka-sack for an easy task for a new comer. He said to make one. If u can find some too that would be great

**Comment by YoshithaRathnayake** [comment]
> @YoshithaRathnayake I asked from @jayasanka-sack for an easy task for a new comer. He said to make one. If u can find some too that would be great

Sure @RandilaP

**Comment by YoshithaRathnayake** [comment]
@RandilaP what is this? 
- #1499

We can tell him/her to do this no?

**Comment by RandilaP** [comment]
@YoshithaRathnayake  I made this from the wrong account. So I closed it

**Comment by dilankavishka** [comment]
may i work on this?

**Comment by jayasanka-sack** [comment]
> I think I asked to increase the gap in this from @jayasanka-sack ayya or from @anjula-sack ayya, one of them told it is ok no need to fix it @RandilaP

Yes. @YoshithaRathnayake is correct. Here's the link to the discussion. 
https://github.com/sef-global/sef-site/pull/1380#issuecomment-1297195424

**Comment by YoshithaRathnayake** [comment]
> may i work on this?

@RandilaP?

**Comment by jayasanka-sack** [comment]
@RandilaP, just wanted to double check with you. Is the reason for increasing the gap because it's partially visible on the screen? 

If that's the case, increasing the gap may not fully solve the issue as different screen sizes render it differently. Check this PR comment for some screenshots https://github.com/sef-global/sef-site/pull/1380#issuecomment-1297195424. Let me know if I'm misunderstanding anything here. Thanks for opening the issue, btw! 🤗

**Comment by jayasanka-sack** [comment]
A possible newbie task would be to fix images on the blog cards. Currently, the images appear stretched and it would be better to have them properly cropped. 

<img width="1241" alt="Screenshot 2023-01-28 at 18 44 59" src="https://user-images.githubusercontent.com/33048395/215268315-486cd4a8-9540-4c0b-9daf-f1cc23cfe9aa.png">

Possible solution:  [CSS object-fit](https://www.digitalocean.com/community/tutorials/css-cropping-images-object-fit)
Bootstrap may already have a helper class.

**Comment by RandilaP** [comment]
@jayasanka-sack Sure. So should I close this PR and make another one.

**Comment by jayasanka-sack** [comment]
> @RandilaP, just wanted to double check with you. Is the reason for increasing the gap because it's partially visible on the screen?

No, the issue should not be closed yet. I apologize if my previous comment was unclear. I just wanted to confirm that the reason for increasing the gap is because it's partially visible on the screen. Can you please clarify what problem you're trying to solve by increasing the gap? This will help to understand the issue better and provide a more specific solution

Regarding the blog images, yes please go ahead and create an issue. It would be greatly appreciated. ❤️

**Comment by ifham-mohamed** [comment]
Hi @jayasanka-sack , @YoshithaRathnayake !

still is this #1500 issue need to be fix, if yes shall i work on this.

**Comment by YoshithaRathnayake** [comment]
> Hi @jayasanka-sack , @YoshithaRathnayake !
> 
> still is this #1500 issue need to be fix, if yes shall i work on this.

No, this issue should not be fixed as Jaye ayya said @ifhammohamed1111

**Comment by ifham-mohamed** [comment]
> > Hi @jayasanka-sack , @YoshithaRathnayake !
> > still is this #1500 issue need to be fix, if yes shall i work on this.
> 
> No, this issue should not be fixed as Jaye ayya said @ifhammohamed1111

Thank you @YoshithaRathnayake for point out to me !
