### ISSUE TITLE
Removing an Unnecessary Section

### ISSUE THREAD

**Issue by akshika47** [sef-global/sef-site#880]
**Describe the bug**
Need to remove the section shown in the screenshot from the "Team Page" as it doesn't add value and distracts the people who visit the page.

**To Reproduce**

**Expected behaviour**
Remove "Meet Our Team
Success of every organization depends on the team
and we got the "right" team" Section

**Screenshots**
![image](https://user-images.githubusercontent.com/4003135/109374628-b503de80-78dc-11eb-876a-9f4cac4a7272.png)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
This is not exactly a bug, but a removal of an extra text content

**Comment by 96RadhikaJadhav** [comment]
@akshika47 Can I work on the issue?

**Comment by janethavi** [comment]
Hi @akshika47, a small opinion on this. 
I also agree that this section doesn't add any value to the site. But if we talk from the site consistency perspective, all the other pages have a small introduction and a vector image on top. By removing this section this page might look odd when comparing with other pages. WDYT if we add a vector image to this section instead of removing the section?

**Comment by akshika47** [comment]
Thank you for your suggestion @janethavi 
So, we initially had a hero image for this page and we removed it, but this section was left for some reason which I don't know why. We need to update all the web pages I agree and I think we should add relevant hero images, ideally of real people and SEF related images. 

Since the team page already has people, we can remove this. After that let's put in a project to restructure the SEF web page.

**Comment by akshika47** [comment]
@96RadhikaJadhav please work on this!

@janethavi let's have a chat regarding website UI upgrades in today's general meeting.
